language: python
cache: pip

python:
  - "3.6"

services:
  - mongodb

env:
  - MONGO_HOST=127.0.0.1
  - MONGO_PORT=27017

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run manage.py test

after_success:
  - codecov -e DJANGO
